config/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("shop.urls")),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name    = "shop"
urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('pattern/', views.pattern, name="pattern"),
    path('pattern_mod/', views.pattern_mod, name="pattern_mod"),
    path('pattern_mod/<int:pk>/', views.pattern_mod, name="pattern_mod_single"),
]

shop/forms.py
from django import forms 
from .models import Pattern,PatternRecipe,Contact,Product,Cart,Order,OrderDetail,OrderDetailPattern

class PatternForm(forms.ModelForm):

    class Meta:
        model   = Pattern
        fields  = [ "title","img","size","user" ]

class PatternRecipeForm(forms.ModelForm):

    class Meta:
        model   = PatternRecipe
        fields  = [ "target","color","number","user" ]

class ContactForm(forms.ModelForm):
    class Meta:
        model   = Contact
        fields  = [ "subject","content","ip","user","email" ]


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        print("フォームクラスの後処理")



"""

#顧客がカートに追加した時に使うフォーム
class CartAddForm(forms.ModelForm):
    class Meta:
        model   = Cart
        fields  = [ "user","product","pattern","amount" ]

#顧客が注文した時に格納するフォーム(注文済みにチェックを入れる。)
class CartOrderForm(forms.ModelForm):
    class Meta:
        model   = Cart
        fields  = [ "user","pattern","ordered" ]

    #注文した時、注文モデルへ複写する。
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

"""
    

shop/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.mixins import LoginRequiredMixin

#DjangoRESTFrameworkを使うため、django.viewsではなくrest_frameworkのviews.APIViewを継承してクラスを作る。これで、PUT,DELETE,PATCHメソッドを受け付ける。
from django.views import View
from rest_framework import views

from django.http.response import JsonResponse

from .models import Pattern,PatternRecipe
from .forms import PatternForm,PatternRecipeForm,ContactForm


#OR検索をするためのクエリビルダを使う
#参照:https://noauto-nolife.com/post/django-or-and-search/
from django.db.models import Q


#TODO:settings.pyに書いてあるDEFAULT_FROM_EMAILを参照するため、settings.pyをimport
from django.conf import settings
from django.core.mail import send_mail



#Djangoメッセージフレームワーク
from django.contrib import messages


class IndexView(views.APIView):

    def get(self, request, *args, **kwargs):

        #TODO:ここでメール送信をする。
        """
        subject = "ここに件名を入れる"
        message = "ここに本文を入れる"

        #運営からのメールであれば、このようにsettings.pyに書いてあるDEFAULT_FROM_EMAILを読み取り、セットする。
        #ユーザー間の送信であれば、ユーザーモデルからメールアドレスを参照する。
        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = [ "hoge@gmail.com" ]

        send_mail(subject, message, from_email, recipient_list)
        """

        patterns    = Pattern.objects.all()
        context     = { "patterns":patterns }

        return render(request,"shop/index.html",context)

index   = IndexView.as_view()


class PatternView(views.APIView):

    def get(self, request, *args, **kwargs):

        #ここはOR検索をするためクエリビルダを使う、|でOR検索、&でAND検索
        query       = Q(user=request.user.id) | Q(user=None)
        patterns    = Pattern.objects.filter(query).order_by("-dt")

        context     = { "patterns":patterns }

        return render(request,"shop/pattern.html",context)

pattern = PatternView.as_view()


#模様の保存、削除、編集を受け付ける。
class PatternModView(LoginRequiredMixin,views.APIView):

    def get(self, request, *args, **kwargs):

        #kwargsにpkがある場合は編集。ない場合は新規作成
        print(kwargs)

        context     = {}

        if "pk" in kwargs:
            #ここは自分が投稿したデータだけ、存在しない場合はリダイレクト
            context["pattern"] = Pattern.objects.filter(id=kwargs["pk"]).first()
            context["recipes"] = PatternRecipe.objects.filter(target=kwargs["pk"]).order_by("id")

        return render(request,"shop/pattern_mod.html",context)


    def post(self, request, *args, **kwargs):
        #模様の保存処理
        json    = { "error":True }

        #ユーザーIDの格納
        copied          = request.POST.copy()
        copied["user"]  = request.user.id

        #ここでもし管理者が投稿しようとした時、サンプルの模様として扱うため、userにはNoneを入れる(ifで分岐)

        print(copied)
        print(request.POST)


        form    = PatternForm(copied, request.FILES)
       
        #アーリーリターン(early return)
        if not form.is_valid():
            print("バリデーションNG")
            return JsonResponse(json)

        print("バリデーションOK")


        #保存するとき、保存したモデルオブジェクトのIDを入手。レシピ登録時に使う。
        pattern = form.save()
        target  = pattern.id

        #まずcolorとnumberがあるかチェック。なければNG
        if "color" not in request.POST or "number" not in request.POST:
            print("バリデーションNG")
            return JsonResponse(json)

        #colorとnumberはそれぞれリスト型なので、.getlist()メソッドを使って呼び出しする。普通にrequest.POST["color"]とすると、得られる値はひとつだけ。
        print(request.POST.getlist("color"))
        print(request.POST.getlist("number"))

        #colorとnumberがリストではない場合はNG
        if type(request.POST.getlist("color")) is not list and type(request.POST.getlist("number")) is not list:
            print("バリデーションNG")
            return JsonResponse(json)

        colors  = request.POST.getlist("color")
        numbers = request.POST.getlist("number")

        for ( color, number ) in zip( colors, numbers ):
            dic             = {}
            dic["color"]    = color
            dic["number"]   = number
            dic["target"]   = target
            dic["user"]     = request.user.id

            print(dic)
            
            form    = PatternRecipeForm(dic)

            if not form.is_valid():
                print("レシピバリデーションNG")
                continue

            print("レシピバリデーションOK")
            form.save()

        json["error"]   = False

        return JsonResponse(json)

    #ここで模様の編集をする
    def put(self, request, *args, **kwargs):
        json    = {"error":True}

        print(kwargs)

        if "pk" not in kwargs:
            return JsonResponse(json)

        pk  = kwargs["pk"]

        #特定のデータを編集する方法
        #https://noauto-nolife.com/post/django-models-delete-and-edit/

        #編集対象を指定
        target  = Pattern.objects.filter(id=pk).first()

        #ここでもしサンプルの模様を編集しようとする場合は、新規作成する

        copied          = request.POST.copy()
        copied["user"]  = request.user.id

        #編集対象を指定した上で、バリデーションをする。(もし編集する際、対象を上書きして編集するのであれば下記を、対象をそのまま残した状態で新規作成(コピー)するのであればinstanceを指定しない。)

        # if "新規作成編集" or "ユーザーがNone(サンプルの模様)":
        #   form    = PatternForm(copied, request.FILES)
        #else
        #   form    = PatternForm(copied, request.FILES, instance=target)


        form    = PatternForm(copied, request.FILES, instance=target)


        #レシピも同様に編集対象を特定してバリデーションをする。
        #編集対象のinstanceを指定するだけでPOSTと同じ処理が続くため、ここは一元化させたほうが良いかも知れない。

        #アーリーリターン(early return)
        if not form.is_valid():
            print("バリデーションNG")
            return JsonResponse(json)

        print("バリデーションOK")

        #保存するとき、保存したモデルオブジェクトのIDを入手。レシピ登録時に使う。
        pattern = form.save()
        target  = pattern.id


        #まずcolorとnumberがあるかチェック。なければNG
        if "color" not in request.POST or "number" not in request.POST:
            print("バリデーションNG")
            return JsonResponse(json)

        #colorとnumberがリストではない場合はNG
        if type(request.POST.getlist("color")) is not list and type(request.POST.getlist("number")) is not list:
            print("バリデーションNG")
            return JsonResponse(json)

        colors  = request.POST.getlist("color")
        numbers = request.POST.getlist("number")


        #レシピ登録で違うのはここだけ。ここでレシピの編集を行う直前、編集前のレシピは全て削除する。
        old_recipes = PatternRecipe.objects.filter(target=pk)
        old_recipes.delete()

        for ( color, number ) in zip( colors, numbers ):
            dic             = {}
            dic["color"]    = color
            dic["number"]   = number
            dic["target"]   = target
            dic["user"]     = request.user.id

            print(dic)
            
            form    = PatternRecipeForm(dic)

            if not form.is_valid():
                print("レシピバリデーションNG")
                continue

            print("レシピバリデーションOK")
            form.save()

        json["error"]   = False
        

        return JsonResponse(json)


pattern_mod = PatternModView.as_view()



#お問い合わせのビュー
class ContactView(views.APIView):

    def get(self, request, *args, **kwargs):
        #requestオブジェクトからIPアドレスとUAを取得してレンダリングさせる。
        #https://noauto-nolife.com/post/django-show-ip-ua-gateway/

        ip_list = request.META.get('HTTP_X_FORWARDED_FOR')
        if ip_list:
            ip  = ip_list.split(',')[0]
        else:
            ip  = request.META.get('REMOTE_ADDR')

        if request.user.is_authenticated:
            email   = request.user.email
        else:
            email   = ""

        context             = {}
        context["ip"]       = ip
        context["email"]    = email

        return render(request,"shop/contact.html",context)

    def post(self, request, *args, **kwargs):

        ip_list = request.META.get('HTTP_X_FORWARDED_FOR')
        if ip_list:
            ip  = ip_list.split(',')[0]
        else:
            ip  = request.META.get('REMOTE_ADDR')

        copied          = request.POST.copy()
        copied["ip"]    = ip

        #ログインしていない人はNoneが、ログインした人はid(UUID)が格納される
        copied["user"]  = request.user.id

        print(request.user.id)
        
        form    = ContactForm(copied)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
            messages.success(request, "お問い合わせ承りました。")

        else:
            print("バリデーションNG")
            messages.error(request, "お問合わせの送信に失敗しました")

        return redirect("shop:contact")

contact = ContactView.as_view()


class SingleView(views.APIView):

    def get(self, request, *args, **kwargs):
        #ここで商品個別を表示
        pass

    def post(self, request, *args, **kwargs):
        #ここでカートに入れる。
        pass


class CartView(views.APIView):
    def get(self, request, *args, **kwargs):
        #ここでカートの中身を表示
        pass

    def post(self, request, *args, **kwargs):
        #ここで配送先の住所をOrder,OrderDetail,OrderDetailPatternへ記録し、CheckoutViewへリダイレクト
        pass

class CheckoutView(views.APIView):

    #このビューのpkはOrderのid。これを元に支払いする金額、商品などを特定する。
    #ただし、リクエストしたユーザーとオーダーのuserが一致している事を確認するなどの対策必要
    def get(self, request, pk, *args, **kwargs):
        #注文内容と配送先を確認させ、決済をしてもらう。(Stripeを使用しない場合は、ここで振込先の銀行口座等を表示)
        #ここでStripeのセッションを作成。顧客に決済をさせる
        """
        具体的には
        - Stripeの秘密鍵をセットしてセッションを開始

        - items_listにカートの中身を全てセット
        - 成功時のURLをCheckoutSuccessViewへセット
        - 失敗時のURLをCheckoutErrorViewへセット
        """
        #ここでセッションを作った時、後に決済処理を特定するため、OrderモデルへStripeセッションID、payment_intentも記録する。
        pass


class CheckoutSuccessView(views.APIView):
    def get(self, request, pk, *args, **kwargs):
        pass

class CheckoutErrorView(views.APIView):
    def get(self, request, pk, *args, **kwargs):
        pass

templates/shop/contact.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>お問い合わせ</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<style>
.message_info{ background:deepskyblue; }
.message_error{ background:crimson; }
.message_success{ background:forestgreen; }


</style>


</head>
<body>

    <!--↓追加-->
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% for message in messages %}
    <div class="message_{{ message.tags }}">{{ message }}</div>
    {% endfor %}





    <p>あなたのIPアドレスは {{ ip }} です。</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input class="form-control" type="text" name="subject" placeholder="件名">
        <input class="form-control" type="email" name="email" value="{{ email }}">
        <textarea class="form-control" name="content" placeholder="お問い合わせ内容"></textarea>
        <input class="form-control" type="submit" value="送信">
    </form>


</body>
</html>

templates/shop/index.html
{% extends "common/base.html" %}
{% load static %}

{% block extra_head %}



{% endblock %}


{% block main_area %}
    <main class="container">

    <a href="{% url 'shop:pattern' %}">模様を作る</a>


    </main>
{% endblock %}

templates/shop/pattern.html
{% extends "common/base.html" %}
{% load static %}


{% block extra_head %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="{% static 'shop/js/script.js' %}"></script>
<script src="{% static 'shop/js/ajax.js' %}"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
{% endblock %}


{% block main_area %}
<main class="container">

    <i class="fab fa-angrycreative" style="font-size:10rem;color:orange;"></i>
    
    {% comment %}
    <form id="pattern_form" action="" method="POST">
        {% csrf_token %}

        <div class="row my-4">
            <div class="col-sm-6">
                <div>コントローラ</div>

                <div id="init_control" class="control">
                    <div>色: <input class="color" type="color" name="color"></div>
                    <div>本数: <input class="number" type="range" name="number" min="1" max="10" step="1" value="1">
                               <input class="number" type="number" min="1" max="10" step="1" value="1"></div>
                    <input class="btn btn-danger control_delete" type="button" value="削除">
                </div>

                <div id="control_area"></div>

                <div>糸の太さ: <input class="size" type="range" name="size" min="1" max="10" step="1" value="1">
                               <input class="size" type="number" min="1" max="10" step="1" value="1"></div>
                <div>方向: <input id="direction" class="direction_chk" type="checkbox"><label class="direction_label" for="direction"></label></div>

                <input id="control_add" class="btn btn-success" type="button" value="追加">

            </div>
            <div class="col-sm-6">
                <div>プレビュー</div>
                <canvas id="canvas" width="300" height="300" style="border:solid 1px black;"></canvas>
            </div>
        </div>

        <input class="form-control" type="text" name="title" placeholder="模様のタイトルを指定してください">

        <!--TODO:ここはtype="submit"にすると普通のフォーム送信が始まる。Ajaxで送信する為にtype="button"にする。-->
        <input id="pattern_submit" type="button" value="送信"> 
    </form>
    {% endcomment %}

    <a class="btn btn-outline-success" href="{% url 'shop:pattern_mod' %}">模様新規作成</a>


    {% for pattern in patterns %}
    <div class="border">
        <div><a href="{% url 'shop:pattern_mod_single' pattern.id %}">{{ pattern.title }}</a></div>
        <img src="{{ pattern.img.url }}" alt="画像">
    </div>
    {% endfor %}

</main>
{% endblock %}


{% comment %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>ショップ</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">

    <!--jQueryと模様を作るJavaScriptの読み込み-->
    <!--
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{% static 'shop/js/script.js' %}"></script>
    -->

</head>
<body>

    <main class="container">

        <div class="row my-4">

            <div class="col-sm-6">
                <div>コントローラ</div>


                <div id="init_control" class="control">
                    <div>色: <input class="color" type="color" name="color"></div>
                    <div>本数: <input class="number" type="range" name="number" min="1" max="10" step="1" value="1">
                               <input class="number" type="number" min="1" max="10" step="1" value="1"></div>
                    <input class="btn btn-danger control_delete" type="button" value="削除">
                </div>

                <div id="control_area"></div>

                <div>糸の太さ: <input class="size" type="range" name="size" min="1" max="10" step="1" value="1">
                               <input class="size" type="number" min="1" max="10" step="1" value="1"></div>
                <div>方向: <input id="direction" class="direction_chk" type="checkbox"><label class="direction_label" for="direction"></label></div>

                <input id="control_add" class="btn btn-success" type="button" value="追加">

            </div>
            <div class="col-sm-6">
                <div>プレビュー</div>
                <canvas id="canvas" width="300" height="300" style="border:solid 1px black;"></canvas>
            </div>

        </div>


        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="img">
            <input type="text" name="title">
            <input type="submit" value="送信">
        </form>

        {% for pattern in patterns %}
        <div class="border">
            {{ pattern.title }}
            <img src="{{ pattern.img.url }}" alt="画像">
        </div>
        {% endfor %}

    </main>






</body>
</html>
{% endcomment %}

templates/shop/pattern_mod.html
{% extends "common/base.html" %}
{% load static %}


{% block extra_head %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="{% static 'shop/js/script.js' %}"></script>
<script src="{% static 'shop/js/ajax.js' %}"></script>
{% endblock %}

{% block main_area %}
<main class="container">

    <!--原本であるこのフォームをformタグに入れてしまうと、これもAjax実行時に送信されてしまうので、formタグの外に出す。-->
    <div id="init_control" class="control">
        <div>色: <input class="color" type="color" name="color"></div>
        <div>本数: <input class="number" type="range" name="number" min="1" max="10" step="1" value="1">
                   <input class="number" type="number" min="1" max="10" step="1" value="1"></div>
        <input class="btn btn-danger control_delete" type="button" value="削除">
    </div>

    <form id="pattern_form" action="" method="POST">
        {% csrf_token %}

        {# ↓action="" なので、編集中はpkにidが入るため、それを利用すれば編集対象のIDは指定する必要はない #}
        <!--
        編集する時は、編集対象のIDをここに
        <input type="hidden" name="" value="{{ pattern.id }}">
        -->

        <div class="row my-4">

            <div class="col-sm-6">
                <div>コントローラ</div>

                <div id="control_area">
                    {% for recipe in recipes %}
                    <div class="control">
                        {{ recipe.id }}
                        <div>色: <input class="color" type="color" name="color" value="{{ recipe.color }}"></div>
                        <div>本数: <input class="number" type="range" name="number" min="1" max="10" step="1" value="{{ recipe.number }}">
                                   <input class="number" type="number" min="1" max="10" step="1" value="{{ recipe.number }}"></div>
                        <input class="btn btn-danger control_delete" type="button" value="削除">
                    </div>
                    {% endfor %}
                </div>
                <div>糸の太さ: <input class="size" type="range" name="size" min="1" max="10" step="1" value="{% if pattern.size %}{{ pattern.size }}{% else %}1{% endif %}">
                               <input class="size" type="number" min="1" max="10" step="1" value="{% if pattern.size %}{{ pattern.size }}{% else %}1{% endif %}"></div>
                <div>方向: <input id="direction" class="direction_chk" type="checkbox"><label class="direction_label" for="direction"></label></div>
                <input id="control_add" class="btn btn-success" type="button" value="追加">
            </div>
            <div class="col-sm-6">
                <div>プレビュー</div>
                <canvas id="canvas" width="300" height="300" style="border:solid 1px black;"></canvas>
            </div>


            <input class="form-control" type="text" name="title" placeholder="模様のタイトルを指定してください" value="{{ pattern.title }}">
            <!--TODO:ここはtype="submit"にすると普通のフォーム送信が始まる。Ajaxで送信する為にtype="button"にする。-->

            {% if recipes %}
            <input id="pattern_mod_submit" type="button" value="編集"> 
            {% else %}
            <input id="pattern_submit" type="button" value="新規作成"> 
            {% endif %}


        </div>
    </form>
</main>
{% endblock %}